### ISSUE TITLE
ecos-ecos-gateway-app-1 is unhealthy

### ISSUE THREAD

**Issue by DeAlexPesh** [Citeck/ecos-community-demo#1]
```
 ✔ Network ecos_app_network                            Created                                                  0.5s
 ✔ Network ecos_default                                Created                                                  0.1s
 ✔ Container ecos-zookeeper-app-1                      Started                                                 12.3s
 ✔ Container ecos-ecos-offers-ecos-apps-1              Started                                                 12.3s  
 ✔ Container ecos-ecos-crm-ecos-apps-1                 Started                                                 18.1s
 ✔ Container ecos-ecos-meetings-ecos-apps-1            Started                                                 12.7s
 ✔ Container ecos-mailhog-app-1                        Started                                                 12.4s
 ✔ Container ecos-rabbitmq-app-1                       Healthy                                                 42.7s
 ✔ Container ecos-ecos-microservices-postgresql-app-1  Healthy                                                 35.1s
 ✔ Container ecos-ecos-order-pass-ecos-apps-1          Started                                                 12.3s
 ✔ Container ecos-mongodb-app-1                        Healthy                                                 36.1s
 ✔ Container ecos-ecos-common-data-list-ecos-apps-1    St...                                                   13.9s
 ✔ Container ecos-ecos-assignments-ecos-apps-1         Started                                                 14.6s
 ✔ Container ecos-ecos-time-tracking-ecos-apps-1       Start...                                                14.0s
 ✔ Container ecos-ecos-registry-app-1                  Healthy                                                 75.1s
 ✔ Container ecos-only-office-app-1                    Started                                                 17.9s
 ✔ Container ecos-ecos-service-desk-app-1              Started                                                 76.8s
 ✔ Container ecos-ecos-ecom-app-1                      Started                                                 76.8s
 ✔ Container ecos-ecos-model-app-1                     Started                                                 69.5s
 ✔ Container ecos-ecos-notifications-app-1             Started                                                 69.6s
 ✔ Container ecos-ecos-uiserv-app-1                    Started                                                 75.1s
 ✔ Container ecos-ecos-identity-app-1                  Started                                                 27.1s
 ✔ Container ecos-ecos-history-app-1                   Started                                                 69.5s
 ✘ Container ecos-ecos-gateway-app-1                   Error                                                 1498.2s
 ✔ Container ecos-ecos-apps-app-1                      Started                                                 75.6s
 ✔ Container ecos-ecos-process-app-1                   Started                                                 68.7s
 ✔ Container ecos-ecos-proxy-app-1                     Created                                                  0.5s
dependency failed to start: container ecos-ecos-gateway-app-1 is unhealthy

```

**Comment by DeAlexPesh** [comment]
Человек создававший конфигурации композа мягко говоря ~~битый~~ альтернативно думающий...
Ну да ладно, мжт он уже вырос и набрался опыта, но:
1. Сделай ты один .env, а не пхай все по разным папкам ~~(эт ж ёбу дать можно)~~.
2. Нейминг контейнеров шедеврален (два раза не повторяю повторяю)
3. Хостнеймы на отъебись ~~как в прочем и~~
Если у кого не получается зайти на пресловутое `"http://ecos-community-demo"`, вы в `ecos-proxy-app.yaml`'е поменяйте значение `hostname: ecos-community-demo`
5. За фичу с ~~мертвыми душами~~ запускающимися один раз контейнерами - отдельный респект
6. ...

~~Долго думал...~~

**Comment by ikaygorodov** [comment]
Добрый день, комментарии ваши приняли, хоть и не со всем согласны =)

Пришлите пожалуйста лог ecos-gateway-app:

`docker-compose logs ecos-gateway-app`

**Comment by ikaygorodov** [comment]
И подскажите на каком объеме ОЗУ вы запускаете систему?

**Comment by DeAlexPesh** [comment]
Запускал на VirtualBox, конфигурация "игровой": Ubyntu 22, 4 ядра, 4 гига, ссд, оно наедается и спит, с восемью вроде даже что-то работает.

Для размышлений: https://github.com/DeAlexPesh/ecos-docker-compose
env'ы всеравно бы растолкать по yaml'ам

~~у вас сравнение сломалось: https://www.citeck.ru/products/compare-versions/~~

**Comment by ikaygorodov** [comment]
По системным требованиям мы рекомендуем запускаться на 16Гб ОЗУ.
https://citeck-ecos.readthedocs.io/ru/latest/admin/docker-compose.html

Более ранние версии системы включали в себя также систему Alfresco, которая и занимала существенную часть данного объема, однако не думаю что у вас получится корректно запуститься меньше чем на 12 Гб.

Также данная поставка предназначена для тестирования локально (не в отдельной виртуальной машине). Если вы хотите запустить в отдельной VM нужны будут корректировки конфигурации Keycloak.
Это связано с спецификой работы Keycloak - для того чтобы выстроить всю систему аутентификации необходимо наличие DNS записи.

**Comment by ikaygorodov** [comment]
По ENV файлам, они также как и yaml файлы генерируются с помощью CI на основе шаблонов и файлов с ответами  и соответственно набор yaml и env файлов может отличаться в зависимости от заказчика. Именно поэтому они разделены. Обычно их в ручную не модифицируют.

**Comment by DeAlexPesh** [comment]
Поставка представлена для ознакомления, это я понял. Странно где-то находил от 4Gb. ну да ладно. Оно запустилось и работает на 8Gb, львиную долю жрет как не странно onlyoffice... C Id сервером все понятно, но в манулах все еще мапингом занимается alfresco, жаль ldap странно работает, если завести его во внутреннем keycloak'е... Но эти плюшки, не смотря на громкое community, как обычно приберегли для энтерпрайза.
По формированию композа тоже понял "пластмассовый мир победил", девелоп пошел в сторону каши из скриптов(
Благодарю. Было интересно.
А нормальная комьюнити версия, на тех же версиях образов работает и где можно посмотреть лайтесты?

**Comment by ikaygorodov** [comment]
Все исходники community версии на ежедневной основе реплицируются на Github.
Релизы выпускаются раз в месяц, обычно в районе 25'го числа, следующий 4.6.

Community версия с точки зрения платформы отличается минимально, отсутствуют толь часть готовых интеграций, а также инструменты типа ЭЦП. Часть функционала платформы еще отвязывается от Alfresco, поэтому некоторые возможности которые вы ожидаете увидеть только в Enterprise просто еще в работе (отвязываем от Alfresco).
Основные отличия Enterprise версии в наличии готовых функциональных модулей например Service Desk или CRM.

**Comment by ikaygorodov** [comment]
В итоге все запустилось? Все в порядке?

**Comment by DeAlexPesh** [comment]
Да, благодарю. все запустилось, но отсутствует ldap'а и некоторые другие вещи хочется...
> Все исходники community версии на ежедневной основе реплицируются на Github.

а имиджи докер с этих обновлений создаются? или где-то можно найти Dockerfile'ы?

**Comment by ikaygorodov** [comment]
Создаются, каждый день, но вот насколько они доступны публично пока не понимаю. Постараюсь ответить вам в понедельник-вторник.

**Comment by DeAlexPesh** [comment]
> Создаются, каждый день, но вот насколько они доступны публично пока не понимаю. Постараюсь ответить вам в понедельник-вторник.

ty, for answer

**Comment by ikaygorodov** [comment]
Прошу прощения что не ответил оперативно. Пока что ежедневные сборки не публикуем.
Стабильные сборки выходят приблизительно раз в месяц.
